#!/bin/sh

remote="$1"
url="$2"
protected_remote="production"

if [ $protected_remote = $remote ]
then
  read -p "You're about to push to ($protected_remote) ($url), are you sure? [y|n] " -n 1 -r < /dev/tty
  echo
  if echo $REPLY | grep -E '^[Yy]$' > /dev/null
  then
    exit 
  fi
  exit 1
else
  exit 0
fi
